DISCORD_WEBHOOK_LOCAL_URL: https://discord.com/api/webhooks/1245307734996549723/qNOGhU5xk20lpQPYSs4w6pFublYVQ8bOqzhmvfhFgFH8WqPH-QPxkzPulzZjaMyYhFIK
DISCORD_WEBHOOK_DEV_URL: https://discord.com/api/webhooks/1245310797282807808/VSRC01VGZjSqVjj3rmGcP8U_xQVYxIWzYazQLuNS7DwY8PUF6UVRzC_ttHZak3s4SDKk
DISCORD_WEBHOOK_PROD_URL: https://discord.com/api/webhooks/1252858737061003366/7zBQ-oDuLxFvQBeuO_I0lLsUj9P8VL9-XaNvoOTfhJx7WSsouabYaefLGWGIJysJzkXg
PORTONE_REST_KEY: 8547725621517476
PORTONE_SECRET_KEY: BMdoSuASpZCRGP0MHh4HhTTW5Aq2gZQZNnIDScsgSDE4NaRSSpgT9DaMvawOXgRuWEqHlEd8MwLx2njh