jwt:
  header: Authorization
    secret: 123nnk14kl3n4kl23lk3n4l
    expiration: 86400000
    tokenPrefix: Bearer
    tokenType: JWT
    issuer: http://localhost:8080
    audience: http://localhost:8080
    filterUrl: /api/v1/auth/**
    