DISCORD_WEBHOOK_LOCAL_URL: https://discord.com/api/webhooks/1245307734996549723/qNOGhU5xk20lpQPYSs4w6pFublYVQ8bOqzhmvfhFgFH8WqPH-QPxkzPulzZjaMyYhFIK
DISCORD_WEBHOOK_DEV_URL: https://discord.com/api/webhooks/1245310797282807808/VSRC01VGZjSqVjj3rmGcP8U_xQVYxIWzYazQLuNS7DwY8PUF6UVRzC_ttHZak3s4SDKk
DISCORD_WEBHOOK_PROD_URL: https://discord.com/api/webhooks/1245310797282807808/VSRC01VGZjSqVjj3rmGcP8U_xQVYxIWzYazQLuNS7DwY8PUF6UVRzC_ttHZak3s4SDKk
